### ISSUE TITLE
player-mpris-tail does not correctly get artist

### ISSUE THREAD

**Issue by 7596ff** [polybar/polybar-scripts#107]
Using spotifyd, `playerctl metadata` returns something like 

`'xesam:album': <'Soundtracks For The Blind'>, 'xesam:title': <'Red Velvet Corridor'>, 'mpris:length': <int64 185120>, 'xesam:artists': <('Swans',)>}`

Somehow it always returns `xesam:artists` instead of `xesam:artist` as the script is expecting. 

I tried changing line 227 to `artist = _getProperty(self._metadata, 'xesam:artists', [''])` but I'm getting `TypeError: object of type 'NoneType' has no len()`. I don't know where to go from here since I don't know the internals of the libraries it uses, but figured one should know.

**Comment by x70b1** [comment]
@Cybolic We need you :v:

**Comment by OxSon** [comment]
I have not been able to reproduce this behavior with the regular Spotify application. I haven't used `spotifyd` myself but it would seem to me the issue lies there. Do you have the same issue with the Spotify app available from the AUR?
