### ISSUE TITLE
mpris-player-tail does not update after closing the player

### ISSUE THREAD

**Issue by Rapiz1** [polybar/polybar-scripts#168]
**OS**
Arch Linux
**Steps to reproduce:**
1.  Play anything (with SMPlayer in my case)
2. Close the player
3. The module remains playing state and will not disappear

**Comment by x70b1** [comment]
@Rapiz1 Thanks for your report. 

@Cybolic Do you know anything about that?

**Comment by Cybolic** [comment]
I can confirm the behaviour but I don't have a fix at the moment.

**Comment by x70b1** [comment]
I guess it's related to a "bug" in polybar. You have to print "nothing" to delete old output. Like `echo ""`. Maybe thats the problem?

**Comment by patrick96** [comment]
This is not a polybar bug. It's intended behavior that the output stays on the bar until it is overwritten by a new line.

**Comment by Rapiz1** [comment]
@Cybolic Any update on this?

**Comment by x70b1** [comment]
@Rapiz1 the fix is merged. Maybe you can test it and give some feedback.
