### ISSUE TITLE
improve info-twitch-countdown

### ISSUE THREAD

**Issue by x70b1** [polybar/polybar-scripts#170]
The script `info-twitch-countdown` triggers a chromium.

Due to the high performance requirements this is a bad solution. We should improve this situation. Otherwise i would drop this script from `polybar-scripts`.

Since I don't use twitch, I can't contribute much here. 

@132ikl You wrote that script. Are there already ways to improve this? Does this work via APIs? 
Are there any other cool twitch functions that can be accessed through an API? Maybe other scripts could be writen for twitch. Thanks! :sunglasses:

**Comment by 132ikl** [comment]
I have to take a look into it, however at the time there was no API whatsoever to interact with Streamlabs content. I do not know if this is still the case. This is from a very very long time ago and I should have a better idea how to make it work with normal tools such as curl. I'll probably look into this but if I forget just ping me again in this issue in like 3 weeks.

**Comment by x70b1** [comment]
Sounds good!
Let me know if you find something out.

**Comment by x70b1** [comment]
@132ikl Ping :)

**Comment by 132ikl** [comment]
I don't really have any ideas and I'm very busy right now so I don't have much time to return to this currently. Feel free to do whatever you please with it.

**Comment by x70b1** [comment]
I removed it. 
But as I said, it wasn't because of the basic idea but because of the way it worked. If you find a slimmer solution then I am willing to take it up again.
