### ISSUE TITLE
improve popup-calendar

### ISSUE THREAD

**Issue by x70b1** [polybar/polybar-scripts#171]
The script `popup-calendar` is not in the best condition. The calculations and recommendation in the script are not very clear.

There seem to be issues with multiple monitors.
Also the alignment is wrong if the calendar is on the right corner of a screen.

**Comment by Grannath** [comment]
As a starter, I use this in another script to position things on multiple monitors.

```shell
get_screen_resolution() {
    xdpyinfo | awk '/dimensions:/ { print $2 }'
}
get_main_display_width() {
    xrandr | awk -F '[ +x]' '/primary/ { print $4/2 }'
}
```

I will see when I can start experimenting more on this. I usually work a lot by trial and error on things like this, so I might take a while.

**Comment by x70b1** [comment]
Whats you output of `xdotool getdisplaygeometry --shell`?
I guess the returned valued are different with multiple screens.
