### ISSUE TITLE
player-mpris-tail blacklist doesn't work

### ISSUE THREAD

**Issue by kiikoh** [polybar/polybar-scripts#184]
I am using brave browser and it detects even though i have -b brave and even tried other things like -b brave-browser

**Comment by kiikoh** [comment]
Seems like it should have been fixed from #169 but I still have the issue.

**Comment by x70b1** [comment]
Thanks for you bug report. `player-mpris-tail` is the most buggy one here it seems ..

**Comment by kiikoh** [comment]
i'd say it works better than simple, but yeah, simple never had this issue. Maybe the addition of a whitelist could remedy this problem?

**Comment by x70b1** [comment]
Yes, could be a solution. 
I guess we need one who wants to work on this.

**Comment by Cybolic** [comment]
The problem here is that Brave announces itself as `chromium` for MPRIS, so your blacklist option should be `-b chromium`.

**Comment by x70b1** [comment]
@kiikoh the fix is merged. Maybe you can test it and give some feedback.
