### ISSUE TITLE
system-bluetooth-bluetoothctl: freezes polybar when clicked

### ISSUE THREAD

**Issue by gavsiu** [polybar/polybar-scripts#198]
Is it just me or does the click action freeze polybar? It correctly shows the connected device, but I cant toggle the power. Polybar unfreezes when I kill the script.

**Comment by x70b1** [comment]
That means the whole bar stops and no modules are updating? Sounds bad.

I will check it. But I need some days for it.

**Comment by patrick96** [comment]
Currently click actions unfortunately freeze polybar for the duration the triggered script is running in the foreground, backgrounding the entire `click-left` script should fix this.

**Comment by x70b1** [comment]
@gavsiu Your solution would be:

```
click-left = ~/polybar-scripts/system-bluetooth-bluetoothctl.sh --toggle &
```

I will leave this issue open as I need to fix the config for all modules.
