### ISSUE TITLE
Player-mpris-tail has issues with MellowPlayer.

### ISSUE THREAD

**Issue by keystroke3** [polybar/polybar-scripts#201]
I use player0mris-tail with bspwm on Manjaro. It works fine with other media players but has issues with MellowPlayer. I noticed when a song switches, it displays the info for about a second then displays dbus error message. When I pause the playback, the info comes back and persists. I don't know if this is an issue with mpris or MellowPlayer. I have seen this problem with Deezer and YouTube.

**Comment by x70b1** [comment]
Thx @keystroke3 for this report. We will have to see what the problem is.

/cc @Cybolic

**Comment by dshoreman** [comment]
@keystroke3 Could you run the script in a terminal with the same flags you use in your Polybar config? That way when you change track you should see the full traceback in the terminal which can be pasted here to help debug the issue.

**Comment by keystroke3** [comment]
@dshoreman  I ran it a few times, and this is the average of the results:

```奈 Eagles - Love Will Keep Us A…
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
TypeError: onMPRISSignal() missing 2 required positional arguments: 'properties' and 'signature'
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
TypeError: onMPRISSignal() missing 2 required positional arguments: 'properties' and 'signature'
```
When I switch to the next song, the title is displayed for about half a second and then shows the error.  Pausing and playing, shows the normal mpris output.

**Comment by dshoreman** [comment]
@keystroke3 Yep, that looks just like the second error I found in #194 ;)

Could you try to apply the patch in #200? I believe that should fix it for you.

**Comment by keystroke3** [comment]
Ah, yes @dshoreman. That patch works. It fixed the issues I was having. Now it is all fine.
