### ISSUE TITLE
Question about openweather scripts "ICONS RELATED"

### ISSUE THREAD

**Issue by annata83** [polybar/polybar-scripts#206]
Just real quick, I have the script working fine and its Great, Thanks. 
What I like to Know is where do I put the Icons?.. Currently I have the five fotns and the main mini.css in the same folder as the script but in not working.

**Comment by keystroke3** [comment]
What does your script do? Which icons are you talking about? What is the relationship between your script, mini.css and polybar? Could you show the script?

**Comment by annata83** [comment]
[Here is the Script](https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/openweathermap-fullfeatured) and all the info of how it works, In the Dependencies Sections it has [weather-icons](https://github.com/erikflowers/weather-icons) and the info in that repo says: 

> Place the 5 font files and the main weather-icons.min.css file in your project, with the assumption that the fonts are located up ../ from your CSS directory.

Off course in the Polybar script there is a function to call the Icons but it doesn't work for me or maybe I am not placing them correctly or I truly i don't understand where to put the fonts.

**Comment by x70b1** [comment]
You can either install the fonts via your distribution - if there is a package available: [`ttf-weather-icons`](https://aur.archlinux.org/packages/ttf-weather-icons/)

Or you install them manually: Copy the `.ttf file` from [the source](https://github.com/erikflowers/weather-icons/tree/master/font) to `/usr/share/fonts/weather-icons`. After that run `fc-cache` as root. Thats it.

**Comment by annata83** [comment]
So I did move the fonts requiere by the script into: .local/share/fonts/
Succesfully Run fc-cache -f -v to and after I did an fc-list | grep weather to confirm the output of:
**❯ fc-list | grep weather
/home/niko/.local/share/fonts/weathericons-regular-webfont.ttf: Weather Icons:style=Regular
/home/niko/.local/share/fonts/weathericons-regular-webfont.woff: Weather Icons:style=Regular**

Restart to fully integrate just in case, and still nothing!

**Comment by x70b1** [comment]
Is the font part of your config as [described](https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/openweathermap-fullfeatured#module)?

**Comment by annata83** [comment]
Yes Indeed; Here is the Fonts section inside Polybar config:
#: Fonts
font-1 = "Terminess:size=11.1"
font-2 = "Material Icons:size=13;4"
font-3 = "Weather Icons:size=12;1"

**Comment by x70b1** [comment]
What is the output of `fc-match "Weather Icons"`?

You could also add `label-font = 3` to your weather script module.
