### ISSUE TITLE
PulseAudio memory leak in pulseaudio-tail

### ISSUE THREAD

**Issue by gabrielziegler3** [polybar/polybar-scripts#222]
pulseaudio-tail makes the PulseAudio daemon consume excessive memory as time goes by. I have opened a [bug report](https://bugs.archlinux.org/task/64467) a while ago, but have just recently found out that this script is the cause of the problem.

![](https://snipboard.io/4KWTa5.jpg)

**Comment by x70b1** [comment]
Good catch.
But there' s nothing we can do here. The issue is not ours. All we do is using the`pactl subscribe` command.

You have to ask upstream about this.
