### ISSUE TITLE
system-bluetooth-bluetoothctl: piping commands instead of giving them as arguments

### ISSUE THREAD

**Issue by druckdev** [polybar/polybar-scripts#235]
The system-bluetooth-bluetoothctl script was not working for me because my bluetoothctl version (I am running Ubuntu 18.04, bluetoothctl 5.48) does not accept commands as arguments. It will just start normally and won't exit by itself.
I was able to fix it by consulting https://wiki.archlinux.org/index.php/Bluetooth#Front-ends and changing the script so that the commands are being piped into bluetoothctl as suggested in the wiki.

**Comment by x70b1** [comment]
Thanks for you PR! :sunglasses: 

Thats a bit a `wontfix`. The usage of `/bin/sh` ensures that no specific shell needs to be installed and used.

The most users will use the script with more up to date versions. Also newer versions of Ubuntu are out. 

If this works for you now, thats fine.

**Comment by druckdev** [comment]
Thank you for your reply, that makes sense.

Could we specify a variable that is not used? By doing that /bin/sh can still be used, but the script would be more portable for the different versions.

Also what is with the piping into bluetoothctl?

**Comment by x70b1** [comment]
I use `dash` to, but I dont see any problems here. 

Pipe the args to `bluetoothctl` works, but running the command as argument looks much cleaner and shorter. So I would leave it as it is.
