### ISSUE TITLE
popup-calendar - issue with position (out of screen)

### ISSUE THREAD

**Issue by vtnpp** [polybar/polybar-scripts#238]
For some reasons, I'm having some issues with the calendar X position. As you can see on the screenshot below, the right side is off of my monitor:

![out_of_screen](https://user-images.githubusercontent.com/59181811/80542013-8b241780-89ac-11ea-89dd-c8cfb5d805ce.png)

Here's the position I'd be expecting (screenshot taken after manually moving the calendar window which is in floating state):

![expected_position](https://user-images.githubusercontent.com/59181811/80542011-89f2ea80-89ac-11ea-8720-7dbedba52ec1.png)

Note that the popup-calendar module is the last one in my `polybar` config (`modules-right`). The calendar window X position is fine if I move the module to the left so that it's not the latest in the list.

---

- `popup-calendar.sh`:

```sh
#!/bin/sh

BAR_HEIGHT="25"         # polybar height
BORDER_SIZE="3"         # border size from your wm settings
YAD_WIDTH="222"         # 222 is minimum possible value
YAD_HEIGHT="193"        # 193 is minimum possible value
DATE="$(date +"%H:%M")"

case "$1" in
--popup)
    if [ "$(xdotool getwindowfocus getwindowname)" = "yad-calendar" ]; then
        exit 0
    fi

    eval "$(xdotool getmouselocation --shell)"
    eval "$(xdotool getdisplaygeometry --shell)"

    # X
    if [ "$((X + YAD_WIDTH / 2 + BORDER_SIZE))" -gt "$WIDTH" ]; then #Right side
        : $((pos_x = WIDTH - YAD_WIDTH - BORDER_SIZE))
    elif [ "$((X - YAD_WIDTH / 2 - BORDER_SIZE))" -lt 0 ]; then #Left side
        : $((pos_x = BORDER_SIZE))
    else #Center
        : $((pos_x = X - YAD_WIDTH / 2))
    fi

    # Y
    if [ "$Y" -gt "$((HEIGHT / 2))" ]; then #Bottom
        : $((pos_y = HEIGHT - YAD_HEIGHT - BAR_HEIGHT - BORDER_SIZE))
    else #Top
        : $((pos_y = BAR_HEIGHT + BORDER_SIZE))
    fi

    yad --calendar --undecorated --fixed --close-on-unfocus --no-buttons \
        --width=$YAD_WIDTH --height=$YAD_HEIGHT --posx=$pos_x --posy=$pos_y \
        --title="yad-calendar" --borders=0 >/dev/null &
    ;;
*)
    echo " $DATE"
    ;;
esac
```

- polybar config:

```sh
[bar/mybar]
width = 100%
height = 25

[module/popup-calendar]
type = custom/script
exec = ~/dotfiles/polybar/.config/polybar/popup-calendar.sh
interval = 1
click-left = ~/dotfiles/polybar/.config/polybar/popup-calendar.sh --popup &
```

- `polybar -v`:

```sh
polybar 3.4.0-96-gfc42da81
```

- `yad --version`:

```sh
6.0 (GTK+ 3.24.20)
```

- `bspwm -v`:

```sh
0.9.7-10-g2ffd9c1
``` 

- `bspwmrc`:

```sh
bspc rule -a Yad   state="floating"
```

Any idea?

Thanks.

**Comment by x70b1** [comment]
I guess the script try to use the cursor as center. Thats why it is outside of the screen.
But in cases like this the script should place it at the corner - but seems not to work.

**Comment by x70b1** [comment]
Unfortunately I can't reproduce it here. But I use `i3wm`.
You're goanna have to try something around which is wrong here.
