### ISSUE TITLE
player-mpris-simple: Permission Denied

### ISSUE THREAD

**Issue by FrenzyExists** [polybar/polybar-scripts#249]
Issue: As an alternative from mpd I decided to try mpris to see the music title and so on at my polybar. However ,for some reason I am getting permission denied from my polybar as seen here:

![Screenshot_20200524_101721](https://user-images.githubusercontent.com/47986470/82756360-cea15400-9da7-11ea-870b-ee51ae93903c.png)

P.S. I am kind of a novice in terms of scripting, so I apologize if the solution was too dumb-simple and I couldn't see it.

**Comment by x70b1** [comment]
As in [setup](https://github.com/polybar/polybar-scripts#setup): run `chmod +x ...`.

**Comment by FrenzyExists** [comment]
It seems that it doesn't work

![image](https://user-images.githubusercontent.com/47986470/82756821-86376580-9daa-11ea-8141-7851354c181f.png)

I hit at the terminal as the link suggested:
chmod +x player-mpris-simple.sh

**Comment by x70b1** [comment]
What happen if you run the script in a terminal?

**Comment by FrenzyExists** [comment]
Nothing actually, everything seems to run normally, except for the not found message at polybar

**Comment by FrenzyExists** [comment]
This is what I have at the config

[module/player-mpris-simple]
type = custom/script
exec = ~/.config/polybar/scripts/player-mpris-simple.sh
interval = 3
click-left = playerctl previous &
click-right = playerctl next &
click-middle = playerctl play-pause &

**Comment by FrenzyExists** [comment]
Ok, I'm back, somehow for some reason the script is actually working, however, the "Not found" message still persist event if it actually did found the script and the player polybar does respond when I click

**Comment by x70b1** [comment]
Are you sure that the path is correct?

**Comment by FrenzyExists** [comment]
Yep, also, just fixed the issue, while debugging, I forgot to uncomment one of the lines from the original script. It works like a charm!

![image](https://user-images.githubusercontent.com/47986470/82757086-2cd03600-9dac-11ea-8e75-73bf5c235b59.png)

Thanks!
