### ISSUE TITLE
Script fails to handle multiple sockets

### ISSUE THREAD

**Issue by goosewood** [polybar/polybar-scripts#256]
Instead of having only a /tmp/mpvsocket, I have /tmp/mpvSockets/ directory with a few sockets in it. If I modify the python file I can specify which one and then the script works fine.

I guess there just needs to be more logic behind finding the socket. I think the simplest way to handle this is have the newest socket be chosen, changing to the next newest when the chosen one closes.

**Comment by x70b1** [comment]
What script are you talking about?

**Comment by goosewood** [comment]
Oops I got confused with git my bad. Forgot this was in a parent directory. 
player-mpv-tail is what's giving me issue.

**Comment by x70b1** [comment]
The most of the scripts in this repo probably have to be modified.
Sounds cool that you found a way. :sunglasses:
