### ISSUE TITLE
issue with player-mpv-tail names

### ISSUE THREAD

**Issue by Laks0** [polybar/polybar-scripts#271]
Hi, after a few seconds listening to a song, the string "+u}" appears in front of the song. 
![img-2020-09-13-154653](https://user-images.githubusercontent.com/35859490/93025956-b19fc380-f5d8-11ea-99c4-a9e7b04e69fc.png)

**Comment by x70b1** [comment]
@vyachkonovalov What do you think about this?

**Comment by vyachkonovalov** [comment]
Hi. I have no idea. Maybe polybar's devs have changed something. I don't use this module anymore and won't fix it.

**Comment by x70b1** [comment]
polybar has no relation here its obviously from [this line](https://github.com/polybar/polybar-scripts/blob/master/polybar-scripts/player-mpv-tail/player-mpv-tail.py#L65).

I will drop this script from the repo as we have no solution here.
