### ISSUE TITLE
polybarscript: info-wifionice - which font was used?

### ISSUE THREAD

**Issue by itc-ger** [polybar/polybar-scripts#290]
I really like the wifionice script: https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/info-wifionice

Does anyone know which font was used to produce this output (**train icon** an **"7-segment display" text**) : 
![image](https://raw.githubusercontent.com/polybar/polybar-scripts/master/polybar-scripts/info-wifionice/screenshots/1.png)

@x70b1 maybe you could provide a hint, please? ;-)

**Comment by x70b1** [comment]
The train icon should be `Font Awesome 4` or `Font Awesome 5`. The other font is `Digital 7`.
Have fun! :sunglasses:

**Comment by itc-ger** [comment]
Thanks for this rapid anwser :100: :-)

**Comment by itc-ger** [comment]
Unfortunately I experienced some rendering glitches (top cut offs) with the `Digital 7` font.

After some research I found another font named [7-Segment](https://torinak.com/7segment). That font is licensed under SIL OFL - so it seems to be a good alternative for this use case. 
_P.S.: The digits are looking quite the same (however punctiations (i.e. ":") are not monospaced and alphanumeric chars are truly ugly 7-segment with_ `7-Segment`_)_

**Comment by x70b1** [comment]
```
font-2 = Digital\-7 Mono:size=13;4
```
This is my config line. I use a line height of 4. Maybe thats my workaround.

**Comment by itc-ger** [comment]
`Digital-7` looks like this on my system:
![Digital-7 Font Issue](https://user-images.githubusercontent.com/17527538/101836725-364d9f80-3b3e-11eb-86dc-64a0c87cd5f0.png)

The problem in my case seems to be system related. Because the glitches are showing up in `font-manager`, too.
![digital-7 font-manager](https://user-images.githubusercontent.com/17527538/101836831-64cb7a80-3b3e-11eb-8987-df884d93834d.png)

Frankly I have no clue which part of my system causing this issue. But I am pretty sure it has nothing to do with polybar.

**Comment by x70b1** [comment]
Yes. That looks bad. 
I have no idea whats wrong there ..
