### ISSUE TITLE
Am I missing something?

### ISSUE THREAD

**Issue by bograt** [polybar/polybar-scripts#302]
I'm trying to add a module that scrolls mpd's current track. The script outputs fine to the terminal, but I get no output in polybar.

config:
`[module/skroll-mpd]`
`type = custom/script`
`exec = bash ~/.config/polybar/scripts/skroll-mpd.sh`
`format-underline = #ffb52a`
`tail = true`

script:
`#!/bin/bash`
`mpc status | head --lines=1 | skroll -l`

**Comment by x70b1** [comment]
Whats the output if you run it on a shell?

**Comment by poetician** [comment]
In the mean time, there is this: https://github.com/PrayagS/polybar-spotify

**Comment by bograt** [comment]
> Whats the output if you run it on a shell?

The current track in mpd. I realize that I'll have to change some things, to make it rerun on track change, stop when paused, &c., but I still wanna know what I'm missing to get stdout to display in a module.

>In the mean time, there is this: https://github.com/PrayagS/polybar-spotify

Yeah, I'm gonna try to finagle this a bit, too.

**Comment by x70b1** [comment]
> but I still wanna know what I'm missing to get stdout to display in a module.

Polybar prints the last line of the output.

**Comment by bograt** [comment]
> > but I still wanna know what I'm missing to get stdout to display in a module.
> 
> Polybar prints the last line of the output.

In this case, it's not printing any of the output.
