### ISSUE TITLE
Script info-softwarecounter - Which font is used in the showcased screenshot ?

### ISSUE THREAD

**Issue by Atralb** [polybar/polybar-scripts#307]
[Link to script folder](https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/info-softwarecounter)

The README features a pretty screenshot, but there's no information as to which font is used to display those icons (nor about the colors used btw which would be interesting to document too).

Without it, it only displays `#` in lieu of each icon.

Do you perhaps know about this @x70b1 ?

**Comment by x70b1** [comment]
You have to replace the `#` with your own icons. A good tool for this is `gucharmap`. 
See the [Fonts](https://github.com/polybar/polybar/wiki/Fonts) page on the polybar wiki fo more details.

I dont know which font was used there. But I would bet it is `Font Awesome`. 4 or 5.
