### ISSUE TITLE
Softwarecounter: Not displaying the rxvt logo

### ISSUE THREAD

**Issue by HugoGDRM** [polybar/polybar-scripts#314]
Hi, i'm struggling to display the rxvt logo, I added 'urxvt' and 'rxvt' to the 'terminals' combine_guis but nothing happen. I checked with htop to determine the name and it is rxvt for sure.
Thnks

**Comment by HugoGDRM** [comment]
However, chromium and vim logos are displayed perfectly

**Comment by HugoGDRM** [comment]
urxvt-unicode doesn't works

**Comment by x70b1** [comment]
Sorry for the late response. I can confirm the issue. `urxvt` seems not to be detected as terminal. 
If I put it as vim command to the list it works. But thats no stable solution.

@jtambasco contributed it. Maybe he has an idea.
