### ISSUE TITLE
player mpris tail audio control keys not showing

### ISSUE THREAD

**Issue by Anonymous78910** [polybar/polybar-scripts#354]
Hey, first of all thanks for making such a wonderful script. I have used mpristail Output using formatters and Polybar action handlers. While I am able to see name of song and artist I cant see play pause next previous keys. They are not just there. I am new to all this. Please ask for any conf file if needed

**Comment by x70b1** [comment]
Please post your config. This would help.

**Comment by Anonymous78910** [comment]
Here you go:
https://pastebin.com/0BW8rt7P

**Comment by x70b1** [comment]
You have your module config in an external file? Can you add this here?

**Comment by Anonymous78910** [comment]
Yeah they are in seperate files as in polybar-themes.
modules: https://pastebin.com/G5iNeZhN

**Comment by x70b1** [comment]
Could you run your polybar from command line? Something like
```
$ polybar main
```

This should give you some logs. Paste them here.

**Comment by x70b1** [comment]
Do you have some lines like 
```
warn: Dropping unmatched character ⏵ (U+23f5) in ...
```

**Comment by Anonymous78910** [comment]
no such error

**Comment by x70b1** [comment]
I have checked the script. Everything works with it. 
So I would expect an configuration issue.

Could you show a screenshot of what you can see?

**Comment by Anonymous78910** [comment]
![2021-12-06-213301_565x22_scrot](https://user-images.githubusercontent.com/95622069/144880686-76e5fdf7-5942-49c4-b1cf-2a0d5f1d6a54.png)

**Comment by x70b1** [comment]
Unfortunately, I can not reproduce the problem. Reopen this issue if you could find out something if you want.
