### ISSUE TITLE
dunst-snooze not showing icons

### ISSUE THREAD

**Issue by pietryszak** [polybar/polybar-scripts#355]
```
  if [ "$(dunstctl is-paused)" = "true" ]; then
            echo "#1"
        else
            echo "#2"
```
Instead,` echo "#1"` and `echo "#2" ` should be an icon to know a status.
```
if [ "$(dunstctl is-paused)" = "true" ]; then
            echo ""
        else
            echo ""
        fi
```

And in module is better to use interval 5s instead 10s for faster refreshing a status of notifications.

**Comment by x70b1** [comment]
I cant see your font icons. Which one should I install?

**Comment by pietryszak** [comment]
> I cant see your font icons. Which one should I install?

[Nerd fonts](https://github.com/ryanoasis/nerd-fonts)

**Comment by x70b1** [comment]
But I don't like them. FontAwesome is much cooler. What sould I do now?

**Comment by pietryszak** [comment]
> But I don't like them. FontAwesome is much cooler. What sould I do now?

yyyy ... nerd font include fonts awesome XD
![image](https://user-images.githubusercontent.com/45850093/145731941-8de440e1-7a1a-40d1-b47b-db68f9f62acb.png)

**Comment by x70b1** [comment]
I can't install them on my Ubuntu system here. How should I do this?

**Comment by pietryszak** [comment]
> I can't install them on my Ubuntu system here as there is no package for it. How should I do this?

This is not related with this issue. 
The issue is that script as echo show saying nothing numers insted same kind of icon.

**Comment by x70b1** [comment]
> This is not related with this issue.

This is the real point. You want to include an icon font here. But if I have problems with them you say that this is not related.

I just made jokes here. Its totaly clear how to use and install icon fonts. But if I add your icons to the script example a random user will come and ask the same questions. But thats not my job here to answer them. I dont wan't to support users with installing and using icon fonts. And I dont wan't to decide which they should use. I want to provide polybar-scripts. That's the focus. So this is the reason why we use simple replacements like `#` or `#1` here. Everybody should know where an icon is and that it can be replaced. It seems to be very obvious as also you found it out. If you look at the [setup steps](https://github.com/polybar/polybar-scripts#setup) you can read about it.

Please note also this at our main README.md:
> This repository is not an exact blueprint. I guess every script has to be customized to make your Polybar unique. 

So yes, you could decrease the interval. But it will need more cpu cycles then which can be a bad idea if you running on a battery. 
Its up to you to modify the scripts for your own use case.

**Comment by pietryszak** [comment]
Ok but it is bad approach.

End user doesn't know what's mean #1 and #2.
Why hot 6 and  4 or 9 and 1 or 4 and 7. 

A easy change echo  notifications on 
And echo notifications off
change everything. 

If you not prefer to use icons it's OK, yours # choise, but using echo with nothings saying info like 1 and 2 is just stupid.
