### ISSUE TITLE
`pw-record` and `pw-play` no longer have the `--list-targets` flag

### ISSUE THREAD

**Issue by johnhamelink** [polybar/polybar-scripts#369]
Hi there,

As of libpipewire 0.3.51, neither `pw-play`, `pw-cat`, nor `pw-record` have the `--list-targets` flag that `pipewire-microphone.sh` and `pipewire-simple.sh` both require. The output for all three commands is the same:

```
❯ pw-play --version
pw-play
Compiled with libpipewire 0.3.51
Linked with libpipewire 0.3.51
❯ pw-play --list-targets
pw-play: unrecognized option '--list-targets'
<snip>
```

Perhaps the following snippet could be used instead? https://github.com/claudius-kienle/polybar-pipewire-control/blob/master/pipewire-control.bash#L28

**Comment by x70b1** [comment]
Thanks!
Maybe @victortrac has some comments on that.

**Comment by victortrac** [comment]
That's somewhat annoying. :)

PR #371 should fix this.
