### ISSUE TITLE
Script has syntax errors

### ISSUE THREAD

**Issue by Tobito719** [polybar/polybar-scripts#384]
The bash script has some syntax error.
First, the "INTERVAL" variable has no "$" sign where it is used.
Second,  line 51 and 52 has syntax errors
Please fix it

**Comment by x70b1** [comment]
Which script are you talking about?

**Comment by Tobito719** [comment]
network-traffic script has syntax errors in line 51... this was what I was shown when running the script.

**Comment by x70b1** [comment]
Please open a PR to fix that issue. The script works for me.
