### ISSUE TITLE
[bug] info-cava.py is not work

### ISSUE THREAD

**Issue by awarewen** [polybar/polybar-scripts#417]
Info-cava.py script output in the wrong position

https://user-images.githubusercontent.com/53365857/228590251-7c7d0057-0e99-439e-a28d-74a51bc623fe.mp4

OS:  arch linux
Terminal:  kitty
bar: polybar
Run Command:
polybar -c ~/todo/dots-2.0/Configs/eww/mybar/polybar.ini cava& > /dev/null

**Comment by x70b1** [comment]
You should check your used font first.
Your polybar drops the output because the font that you use can not display the chars. That what the warning output is for.

**Comment by awarewen** [comment]
![image](https://user-images.githubusercontent.com/53365857/231452578-4d011eac-829b-482a-8710-a8a763ac6336.png)
I'm sorry to reopen this issue, as I only had time to look into it today due to some other reasons. I have checked the Polybar WIKI and defined a font according to its format, but it seems that the font is not being loaded correctly according to the logs in Polybar. Thank you for this project, it's really cool.

**Comment by awarewen** [comment]
![image](https://user-images.githubusercontent.com/53365857/231459305-f9082f04-844d-4c30-8afe-ccd17bbb2858.png)


https://user-images.githubusercontent.com/53365857/231460039-24256d53-9b29-4a4a-96d3-0202704cdc74.mp4

My Kitty terminal is also using this font. From the status of the widget, it seems that the correct characters have passed the detection and are displayed on the bar, but only as empty characters (I described it poorly).

:crying_cat_face:

**Comment by x70b1** [comment]
polybar should also read the fonts from `/usr/share/fonts`.
Now you use `Iosevka` instead of `Caskaydia`. That could solved the issue. 

The [wiki page](https://github.com/polybar/polybar/wiki/Fonts) is a great start to play around with fonts. 

But yeah, fonts are probably the topic with the most questions on polybar.
