### ISSUE TITLE
I seem to be getting an error for the network-traffic script

### ISSUE THREAD

**Issue by l4n1skyy** [polybar/polybar-scripts#431]
![image](https://github.com/polybar/polybar-scripts/assets/71810630/e4b8be28-8705-4dcb-9b2c-40d637569f56)
@x70b1

**Comment by x70b1** [comment]
Have you configured your interfaces in [line 30](https://github.com/polybar/polybar-scripts/blob/master/polybar-scripts/network-traffic/network-traffic.sh#L30)?

**Comment by l4n1skyy** [comment]
that worked, thanks a lot!!
