### ISSUE TITLE
player-mpris-tail doesn't show any icon

### ISSUE THREAD

**Issue by niels0n** [polybar/polybar-scripts#439]
Hey there, thanks for this awesome script. As the title says, it doesn't show any icon.
In my polybar config I have 

`exec = ~/.config/polybar/scripts/player-mpris-tail.py -f '{icon} {:artist:t25:{artist}:}{:artist: - :}{:t25:{title}:}'`

everything works fine except for the icons. Maybe I have to install a specific set of icons?
I'm on Arch, BTW.

**Comment by x70b1** [comment]
You have to configure icon fonts.

There is a section in the polybar wiki: [polybar/polybar/wiki/Fonts](https://github.com/polybar/polybar/wiki/Fonts#icon-fonts)

**Comment by niels0n** [comment]
I already have 

`font-1 = "Symbols Nerd Font Mono:size=26"`

in config.ini. Isn't that what you mean?

**Comment by x70b1** [comment]
What happens if you run that command in a terminal? Can you see the icons there?

**Comment by niels0n** [comment]
Yes, in a terminal I can see the icons correctly

**Comment by niels0n** [comment]
> correctly

...well, sort of

![Screenshot_2023-10-30_12-12-05](https://github.com/polybar/polybar-scripts/assets/47432766/99623cbf-3a87-4410-9944-9bd6343dda0f)

**Comment by x70b1** [comment]
The terminal an polybar use an icon that is availiable. If you have a better icon in you icon font you can set it manually.

**Comment by x70b1** [comment]
Use `gucharmap` as on the wiki pages described to play around. You can also copy and paste from there.

**Comment by niels0n** [comment]
thank you!
