### ISSUE TITLE
Battery combined shell displays no icons

### ISSUE THREAD

**Issue by indeedwatson** [polybar/polybar-scripts#455]
https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/battery-combined-shell

If I put the module just like that, or if I copy the settings of the default battery module, like so:

```ini
[module/dual-battery]
type = custom/script
interval = 10

exec = "~/.config/polybar/battery-combined-shell.sh"
ramp-capacity0-foreground = ${xrdb:color1}

format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
label-full = %percentage%
format-full-prefix = 
format-full-prefix-foreground = ${colors.primary}
format-full-prefix-padding-right = 1

ramp-capacity-0 = 
ramp-capacity-0-foreground = ${colors.alert}
ramp-capacity-1 = 
ramp-capacity-1-foreground = ${colors.warning}
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${colors.primary}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = ${colors.secondary}
animation-charging-framerate = 750

```

Either way, the module looks like `#23 36 %`

The readme claims the module has "changing icons" so I must be doing something wrong.

The default module does display the battery icons appropriately and I've made the new script executable. Is there a step missing from the readme?

**Comment by x70b1** [comment]
The internal battery plugin is not connected to the script. So you can remove the settings.

What you need is you have to replace the icon in the script file. Take a look what the script is doing:
`#1` = on ac
`#21` = battery > 85% = full
`#22` = battery > 60% = more than a half full

**Comment by indeedwatson** [comment]
> The internal battery plugin is not connected to the script. So you can remove the settings.
> 
> What you need is you have to replace the icon in the script file. Take a look what the script is doing: `#1` = on ac `#21` = battery > 85% = full `#22` = battery > 60% = more than a half full

Thank you, that worked. One last question, since the icons are in the script, how can I change the color of it?

**Comment by x70b1** [comment]
You can use [format tags](https://github.com/polybar/polybar/wiki/Formatting#format-tags). The wiki shows how that works.

If you script prints something like `%{F#f00} red text %{F-}` it will printed in red on your bar.
